# Generated by Django 5.0.6 on 2024-05-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='chaivariety',
            name='pricing',
            field=models.CharField(default='', max_length=50),
        ),
    ]
